spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker_db
spring.datasource.username=postgres
spring.datasource.password=Dh06012006!@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.security.jwt.secret=${JWT_SECRET:}
app.security.jwt.expiration=PT1H
app.security.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}
